export { default as Homepage } from './homepage/Homepage';
export { default as Wesprzyj } from './wesprzyj/Wesprzyj';
export { default as ProjectsAndNews } from './projectsAndNews/ProjectsAndNews';
export { default as ProjectAndNews } from './projectAndNews/ProjectAndNews';
export { default as About } from './about/About';
export { default as Advice } from './advice/Advice';
export { default as FAQ } from './faq/FAQ';
export { default as Contact } from './contact/Contact';
export { default as NotFound } from './notFound/NotFound';