export { default as About } from './about/About';
export { default as Cart } from './cart/Cart';
export { default as Checkout } from './checkout/Checkout';
export { default as Contact } from './contact/Contact';
export { default as Home } from './home/Home';
export { default as Konto } from './konto/Konto';
export { default as Login } from './login/Login';
export { default as NotFound } from './notFound/NotFound';
export { default as Product } from './product/Product';
export { default as Register } from './register/Register';
export { default as ReturnPage } from './returnPage/ReturnPage';
export { default as Sklep } from './sklep/Sklep';
export { default as Wyszukiwarka } from './wyszukiwarka/Wyszukiwarka';
export {default as Success} from './success/Success';