import { Offer } from "../models";

async function offerSeeder() {
    await Offer.insertMany([
        {
            _id: "65a318dfb517b9b39c23d01c",
            title: 'Frontend Developer',
            mode: 'Stacjonarnie',
            location: 'Warszawa',
            level: 'Mid',
            expiresAt: new Date('2024-02-20'),
            contractType: 'Umowa o Pracę',
            salary: 8000,
            requiredTechnologies: ['React.js', 'JavaScript', 'HTML', 'CSS'],
            optionalTechnologies: ['TypeScript', 'Redux', 'Webpack'],
            description: 'Poszukujemy doświadczonego Frontend Developera, który będzie odpowiedzialny za...',
            tasks: ['Rozwój i utrzymanie aplikacji webowych', 'Implementacja nowych funkcji', 'Optymalizacja kodu'],
            required: ['Doświadczenie w pracy z React.js', 'Znajomość HTML i CSS', 'Umiejętność pracy w zespole'],
            optional: ['Znajomość TypeScript', 'Doświadczenie z Redux', 'Znajomość Webpack'],
            benefits: ['Stabilne zatrudnienie', 'Prywatna opieka zdrowotna', 'Elastyczne godziny pracy'],
            recruitmentStages: ['Wstępna rozmowa telefoniczna', 'Rozmowa kwalifikacyjna', 'Test praktyczny'],
            company: '6597d2f7a0eeb1a05d7233b0'
        },
        {
            title: 'Backend Developer',
            mode: 'Hybrydowo',
            location: 'Kraków',
            level: 'Senior',
            expiresAt: new Date('2024-02-25'),
            contractType: 'B2B',
            salary: 12000,
            requiredTechnologies: ['Node.js', 'Express.js', 'MongoDB', 'REST API'],
            optionalTechnologies: ['GraphQL', 'Docker', 'Kubernetes'],
            description: 'Doświadczony Backend Developer poszukiwany do zespołu zajmującego się rozwijaniem i utrzymaniem...',
            tasks: ['Implementacja nowych funkcji backendowych', 'Optymalizacja i skalowanie istniejących systemów', 'Wsparcie przy projektowaniu architektury'],
            required: ['Doświadczenie w pracy z Node.js i Express.js', 'Znajomość MongoDB i projektowania baz danych', 'Umiejętność pracy z systemami kontroli wersji'],
            optional: ['Znajomość GraphQL', 'Doświadczenie w konteneryzacji (Docker, Kubernetes)'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Elastyczne godziny pracy', 'Opieka medyczna'],
            recruitmentStages: ['Wstępna rozmowa kwalifikacyjna', 'Test praktyczny', 'Rozmowa z zespołem technicznym'],
            company: '61f8dce5e7a83129bcdb3f1a'
        },
        {
            title: 'Data Scientist',
            mode: 'Zdalnie',
            location: 'Wrocław',
            level: 'Mid',
            expiresAt: new Date('2024-02-28'),
            contractType: 'Umowa o Pracę',
            salary: 10000,
            requiredTechnologies: ['Python', 'Machine Learning'],
            optionalTechnologies: ['PyTorch', 'Data Visualization'],
            description: 'Poszukujemy doświadczonego Data Scientist, który będzie odpowiedzialny za analizę danych, tworzenie modeli predykcyjnych...',
            tasks: ['Analiza danych i identyfikacja trendów', 'Tworzenie i ocena modeli predykcyjnych', 'Wizualizacja danych'],
            required: ['Doświadczenie w analizie danych i tworzeniu modeli predykcyjnych', 'Znajomość języka Python i bibliotek takich jak Pandas i NumPy', 'Umiejętność pracy z danymi'],
            optional: ['Znajomość TensorFlow lub PyTorch', 'Doświadczenie w wizualizacji danych'],
            benefits: ['Stabilne zatrudnienie w dynamicznie rozwijającej się firmie', 'Elastyczny czas pracy', 'Dostęp do szkoleń'],
            recruitmentStages: ['Rozmowa kwalifikacyjna', 'Test praktyczny', 'Rozmowa z zespołem'],
            company: '61f8dce5e7a83129bcdb3f1a'
        },
        {
            title: 'UX/UI Designer',
            mode: 'Stacjonarnie',
            location: 'Poznań',
            level: 'Mid',
            expiresAt: new Date('2024-03-05'),
            contractType: 'Umowa o Pracę',
            salary: 9000,
            requiredTechnologies: ['Adobe XD', 'Sketch', 'Figma'],
            optionalTechnologies: ['InVision', 'Zeplin', 'Illustrator'],
            description: 'Doświadczony UX/UI Designer poszukiwany do zespołu zajmującego się projektowaniem intuicyjnych interfejsów użytkownika...',
            tasks: ['Tworzenie wireframe\'ów i prototypów', 'Opracowywanie interfejsów użytkownika zgodnie z najnowszymi trendami', 'Współpraca z zespołem developerskim'],
            required: ['Doświadczenie w projektowaniu interfejsów użytkownika', 'Znajomość narzędzi takich jak Adobe XD, Sketch, Figma', 'Umiejętność pracy w zespole'],
            optional: ['Znajomość narzędzi do współpracy z programistami, np. InVision, Zeplin', 'Umiejętność tworzenia ilustracji w Adobe Illustrator'],
            benefits: ['Przyjazne środowisko pracy', 'Możliwość rozwoju zawodowego', 'Elastyczne godziny pracy'],
            recruitmentStages: ['Rozmowa kwalifikacyjna', 'Przedstawienie portfolio', 'Test projektowy'],
            company: '61f8dce5e7a83129bcdb3f1a'
        },
        {
            title: 'IT Project Manager',
            mode: 'Hybrydowo',
            location: 'Łódź',
            level: 'Senior',
            expiresAt: new Date('2024-03-10'),
            contractType: 'B2B',
            salary: 15000,
            requiredTechnologies: ['Agile', 'Scrum', 'Jira'],
            optionalTechnologies: ['MS Project'],
            description: 'Dynamiczna firma poszukuje doświadczonego IT Project Managera, który będzie odpowiedzialny za skuteczne zarządzanie projektami IT...',
            tasks: ['Planowanie, monitorowanie i kontrola projektów IT', 'Współpraca z zespołem developerskim', 'Raportowanie postępów projektów'],
            required: ['Doświadczenie w zarządzaniu projektami IT w metodykach Agile i Scrum', 'Znajomość narzędzi takich jak Jira', 'Umiejętność pracy w zespole'],
            optional: ['Certyfikaty PRINCE2, Kanban lub inne z zakresu zarządzania projektami', 'Znajomość MS Project'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Prywatna opieka zdrowotna', 'Pakiet szkoleń i konferencji branżowych'],
            recruitmentStages: ['Rozmowa kwalifikacyjna', 'Studium przypadku', 'Rozmowa z zarządem firmy'],
            company: '61f8dce5e7a83129bcdb3f1a'
        },
        {
            title: 'DevOps Engineer',
            mode: 'Zdalnie',
            location: 'Gdańsk',
            level: 'Mid',
            expiresAt: new Date('2024-03-15'),
            contractType: 'Umowa o Pracę',
            salary: 11000,
            requiredTechnologies: ['Docker', 'Kubernetes', 'Jenkins', 'AWS'],
            optionalTechnologies: ['Terraform', 'Ansible', 'CI/CD'],
            description: 'Innowacyjna firma IT poszukuje utalentowanego DevOps Engineera, który będzie odpowiedzialny za...',
            tasks: ['Wdrażanie i utrzymanie narzędzi do automatyzacji procesów', 'Konfiguracja i utrzymanie infrastruktury w chmurze', 'Optymalizacja procesów CI/CD'],
            required: ['Doświadczenie w pracy z narzędziami do konteneryzacji (Docker, Kubernetes)', 'Znajomość narzędzi CI/CD, takich jak Jenkins', 'Umiejętność pracy z chmurą AWS'],
            optional: ['Znajomość narzędzi do automatyzacji, np. Terraform, Ansible', 'Doświadczenie w projektowaniu i wdrażaniu procesów CI/CD'],
            benefits: ['Elastyczne godziny pracy', 'Pracę w zespole ekspertów', 'Dostęp do najnowszych technologii'],
            recruitmentStages: ['Rozmowa kwalifikacyjna', 'Praktyczne zadanie', 'Rozmowa z zespołem technicznym'],
            company: '61f8dce5e7a83129bcdb3f1a'
        },
        {
            title: 'UX/UI Designer',
            mode: 'Stacjonarnie',
            location: 'Poznań',
            level: 'Mid',
            expiresAt: new Date('2024-03-20'),
            contractType: 'Umowa o Pracę',
            salary: 8500,
            requiredTechnologies: ['Figma', 'Adobe XD', 'Sketch', 'InVision'],
            optionalTechnologies: ['Illustrator', 'After Effects', 'Usability Testing'],
            description: 'Poszukujemy kreatywnego UX/UI Designera z doświadczeniem w projektowaniu responsywnych interfejsów użytkownika.',
            tasks: ['Projektowanie interfejsów aplikacji webowych', 'Tworzenie wireframe\'ów i prototypów', 'Współpraca z zespołem programistycznym'],
            required: ['Doświadczenie w projektowaniu UX/UI', 'Znajomość narzędzi projektowych (Figma, Adobe XD)', 'Umiejętność pracy w zespole'],
            optional: ['Znajomość narzędzi graficznych (Illustrator, After Effects)', 'Doświadczenie w testach użyteczności'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Pracownia kreatywna', 'Elastyczne godziny pracy'],
            recruitmentStages: ['Analiza portfolio', 'Rozmowa rekrutacyjna', 'Test projektowy'],
            company: '61f8dce5e7a83129bcdb3f1a'
        },
        {
            title: 'Data Analyst',
            mode: 'Hybrydowo',
            location: 'Gdańsk',
            level: 'Junior',
            expiresAt: new Date('2024-03-25'),
            contractType: 'Staż',
            salary: 4000,
            requiredTechnologies: ['SQL', 'Python', 'Pandas', 'Power BI'],
            optionalTechnologies: ['Machine Learning', 'Tableau', 'R'],
            description: 'Dołącz do zespołu jako Junior Data Analyst i rozwijaj umiejętności w obszarze analizy danych oraz raportowania.',
            tasks: ['Analiza danych i przygotowywanie raportów', 'Współpraca z zespołem biznesowym', 'Tworzenie dashboardów w narzędziach BI'],
            required: ['Podstawowa znajomość SQL i Pythona', 'Znajomość narzędzi do analizy danych (Pandas)', 'Dobra analiza matematyczna'],
            optional: ['Zainteresowanie Machine Learningiem', 'Znajomość narzędzi BI (Tableau)', 'Doświadczenie w języku R'],
            benefits: ['Mentorstwo doświadczonego analityka danych', 'Możliwość zdobycia doświadczenia w stażu', 'Praca w nowoczesnym biurze'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Test analityczny', 'Rozmowa z zespołem'],
            company: '61f8dce5e7a83129bcdb3f1a'
        },
        {
            title: 'Mobile App Developer',
            mode: 'Stacjonarnie',
            location: 'Katowice',
            level: 'Senior',
            expiresAt: new Date('2024-04-01'),
            contractType: 'Umowa zlecenie',
            salary: 16000,
            requiredTechnologies: ['Swift', 'Kotlin', 'React Native', 'Flutter'],
            optionalTechnologies: ['RxSwift', 'Jetpack Compose', 'NativeScript'],
            description: 'Dołącz do naszego zespołu jako Mobile App Developer! Poszukujemy doświadczonego programisty z pasją do tworzenia mobilnych aplikacji.',
            tasks: ['Rozwój i utrzymanie aplikacji mobilnych', 'Implementacja nowych funkcji i rozwiązań', 'Optymalizacja kodu i wydajności'],
            required: ['Doświadczenie w programowaniu aplikacji mobilnych (Swift, Kotlin)', 'Znajomość platformy React Native lub Flutter', 'Umiejętność pracy w zespole'],
            optional: ['Znajomość RxSwift lub Jetpack Compose', 'Doświadczenie z NativeScript', 'Umiejętność tworzenia responsywnych interfejsów'],
            benefits: ['Konkurencyjne wynagrodzenie', 'Projekty dla renomowanych klientów', 'Praca w dynamicznym środowisku'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Test praktyczny', 'Rozmowa z zespołem'],
            company: '61f8dce5e7a83129bcdb3f1a'
        },
        {
            title: 'IT Support Specialist',
            mode: 'Zdalnie',
            location: 'Łódź',
            level: 'Mid',
            expiresAt: new Date('2024-04-10'),
            contractType: 'Umowa o dzieło',
            salary: 9000,
            requiredTechnologies: ['Windows Server', 'Active Directory', 'Office 365'],
            optionalTechnologies: ['Linux', 'Network Security', 'ITIL'],
            description: 'Dołącz do naszego zespołu jako Specjalista ds. Wsparcia IT! Poszukujemy osoby z doświadczeniem w obszarze wsparcia technicznego.',
            tasks: ['Wsparcie techniczne dla użytkowników', 'Konfiguracja i utrzymanie systemów Windows Server', 'Rozwiązywanie problemów związanych z oprogramowaniem i sprzętem'],
            required: ['Doświadczenie w obszarze wsparcia IT', 'Znajomość systemów Windows Server i Active Directory', 'Dobra zdolność do rozwiązywania problemów'],
            optional: ['Znajomość systemów Linux', 'Zainteresowanie bezpieczeństwem sieciowym', 'Certyfikat ITIL'],
            benefits: ['Stabilne zatrudnienie', 'Elastyczne godziny pracy', 'Możliwość rozwoju zawodowego'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Test praktyczny', 'Rozmowa z zespołem'],
            company: '61f8dce5e7a83129bcdb3f1b'
        },
        {
            title: 'Marketing Specialist',
            mode: 'Hybrydowo',
            location: 'Kraków',
            level: 'Mid',
            expiresAt: new Date('2024-04-15'),
            contractType: 'Umowa o Pracę',
            salary: 8500,
            requiredTechnologies: ['SEO', 'Google Analytics', 'Social Media Marketing'],
            optionalTechnologies: ['Email Marketing', 'PPC Advertising', 'Marketing Automation'],
            description: 'Dołącz do naszego zespołu jako Specjalista ds. Marketingu! Poszukujemy osoby z doświadczeniem w marketingu cyfrowym.',
            tasks: ['Prowadzenie kampanii marketingowych online', 'Optymalizacja treści na stronie internetowej', 'Analiza danych marketingowych'],
            required: ['Doświadczenie w zarządzaniu mediami społecznościowymi', 'Znajomość technik SEO i Google Analytics', 'Umiejętność tworzenia skutecznych strategii marketingowych'],
            optional: ['Znajomość Email Marketingu', 'Doświadczenie w reklamie PPC', 'Znajomość narzędzi Marketing Automation'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca w dynamicznym zespole', 'Możliwość szkoleń i rozwoju'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza case study', 'Rozmowa z zespołem marketingowym'],
            company: '61f8dce5e7a83129bcdb3f1b'
        },
        {
            title: 'DevOps Engineer',
            mode: 'Zdalnie',
            location: 'Poznań',
            level: 'Senior',
            expiresAt: new Date('2024-04-20'),
            contractType: 'B2B',
            salary: 16000,
            requiredTechnologies: ['Docker', 'Kubernetes', 'Jenkins', 'Ansible'],
            optionalTechnologies: ['Terraform', 'AWS', 'Prometheus'],
            description: 'Poszukujemy doświadczonego inżyniera DevOps do współpracy nad projektami w chmurze. Oferujemy interesujące wyzwania i rozwój umiejętności.',
            tasks: ['Implementacja i utrzymanie infrastruktury w chmurze', 'Automatyzacja procesów deweloperskich', 'Zarządzanie systemami ciągłej integracji i dostarczania'],
            required: ['Doświadczenie w konfiguracji i zarządzaniu Dockerem i Kubernetes', 'Umiejętność obsługi narzędzi CI/CD (Jenkins)', 'Znajomość systemów Linux'],
            optional: ['Znajomość narzędzi do infrastruktury jak Terraform', 'Doświadczenie z chmurą AWS', 'Znajomość monitoring systemów (Prometheus)'],
            benefits: ['Konkurencyjne wynagrodzenie', 'Możliwość pracy zdalnej', 'Projekty w technologii cloud computing'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Test praktyczny', 'Rozmowa z zespołem'],
            company: '61f8dce5e7a83129bcdb3f1b'
        },
        {
            title: 'HR Specialist',
            mode: 'Stacjonarnie',
            location: 'Warszawa',
            level: 'Mid',
            expiresAt: new Date('2024-04-25'),
            contractType: 'Umowa o Pracę',
            salary: 9000,
            requiredTechnologies: ['HR Software'],
            optionalTechnologies: ['Performance Management', 'HR Analytics'],
            description: 'Dołącz do naszego zespołu HR jako Specjalista ds. HR! Poszukujemy osoby z doświadczeniem w zarządzaniu zasobami ludzkimi.',
            tasks: ['Rekrutacja i selekcja kandydatów', 'Obsługa procesów związanych z przyjęciem pracownika', 'Zarządzanie dokumentacją personalną'],
            required: ['Doświadczenie w prowadzeniu procesów rekrutacyjnych', 'Znajomość narzędzi HR Software', 'Umiejętność przeprowadzania rozmów kwalifikacyjnych'],
            optional: ['Znajomość zarządzania wynikami pracowników', 'Wiedza z zakresu prawa pracy', 'Znajomość narzędzi HR Analytics'],
            benefits: ['Stabilne zatrudnienie', 'Pakiet benefitów pozapłacowych', 'Możliwość rozwoju zawodowego'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza case study', 'Rozmowa z kierownictwem'],
            company: '61f8dce5e7a83129bcdb3f1b'
        },
        {
            title: 'Network Security Specialist',
            mode: 'Hybrydowo',
            location: 'Gdańsk',
            level: 'Senior',
            expiresAt: new Date('2024-05-01'),
            contractType: 'B2B',
            salary: 17000,
            requiredTechnologies: ['Firewall', 'Intrusion Detection Systems', 'VPN', 'Network Monitoring'],
            optionalTechnologies: ['SIEM Solutions', 'Penetration Testing', 'Cryptography'],
            description: 'Dołącz do zespołu jako Specjalista ds. Bezpieczeństwa Sieci! Poszukujemy doświadczonej osoby z wiedzą z zakresu zabezpieczeń sieciowych.',
            tasks: ['Konfiguracja i utrzymanie zapór sieciowych', 'Monitorowanie ruchu sieciowego', 'Analiza zagrożeń i zarządzanie incydentami'],
            required: ['Doświadczenie w konfiguracji firewalli i systemów IDS', 'Znajomość technologii VPN', 'Umiejętność monitorowania ruchu sieciowego'],
            optional: ['Znajomość rozwiązań SIEM', 'Doświadczenie w testach penetracyjnych', 'Znajomość kryptografii'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Możliwość pracy zdalnej', 'Projekty w obszarze cyberbezpieczeństwa'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Test praktyczny', 'Rozmowa z zespołem bezpieczeństwa'],
            company: '61f8dce5e7a83129bcdb3f1b'
        },
        {
            title: 'UX/UI Designer',
            mode: 'Stacjonarnie',
            location: 'Wrocław',
            level: 'Mid',
            expiresAt: new Date('2024-05-05'),
            contractType: 'Umowa o Pracę',
            salary: 9500,
            requiredTechnologies: ['Figma', 'Adobe XD', 'Sketch', 'User-Centered Design'],
            optionalTechnologies: ['InVision', 'Prototyping Tools', 'HTML', 'CSS'],
            description: 'Dołącz do naszego zespołu jako Projektant UX/UI! Poszukujemy osoby z kreatywnym podejściem do projektowania interfejsów użytkownika.',
            tasks: ['Projektowanie interfejsów użytkownika', 'Tworzenie wireframe\'ów i prototypów', 'Współpraca z zespołem programistycznym'],
            required: ['Znajomość narzędzi do projektowania jak Figma czy Adobe XD', 'Umiejętność projektowania zorientowanego na użytkownika', 'Doświadczenie w pracy nad interfejsami'],
            optional: ['Znajomość narzędzi do prototypowania jak InVision', 'Podstawowa znajomość HTML/CSS', 'Umiejętność pracy z zespołem programistycznym'],
            benefits: ['Stabilne zatrudnienie', 'Praca w zespole kreatywnym', 'Możliwość udziału w ciekawych projektach'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza portfolio', 'Rozmowa z zespołem projektowym'],
            company: '61f8dce5e7a83129bcdb3f1b'
        },
        {
            title: 'Data Analyst',
            mode: 'Zdalnie',
            location: 'Katowice',
            level: 'Junior',
            expiresAt: new Date('2024-05-10'),
            contractType: 'Umowa o Pracę',
            salary: 7500,
            requiredTechnologies: ['SQL', 'Python', 'Data Visualization', 'Statistical Analysis'],
            optionalTechnologies: ['Machine Learning', 'Big Data Technologies', 'R'],
            description: 'Dołącz do naszego zespołu jako Analityk Danych! Poszukujemy osoby z pasją do analizy danych i wnioskowania na ich podstawie.',
            tasks: ['Analiza danych biznesowych', 'Tworzenie raportów i analiz', 'Współpraca z zespołem ds. business intelligence'],
            required: ['Znajomość języka SQL', 'Umiejętność programowania w Pythonie', 'Doświadczenie w analizie danych biznesowych'],
            optional: ['Podstawowa wiedza z zakresu machine learning', 'Znajomość technologii big data', 'Programowanie w języku R'],
            benefits: ['Elastyczne godziny pracy', 'Praca zdalna', 'Możliwość rozwoju w obszarze analizy danych'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Test umiejętności analitycznych', 'Rozmowa z zespołem BI'],
            company: '61f8dce5e7a83129bcdb3f1b'
        },
        {
            title: 'Mobile App Developer',
            mode: 'Stacjonarnie',
            location: 'Łódź',
            level: 'Mid',
            expiresAt: new Date('2024-05-15'),
            contractType: 'B2B',
            salary: 11000,
            requiredTechnologies: ['React Native', 'Swift', 'Kotlin'],
            optionalTechnologies: ['Flutter', 'Xamarin', 'Firebase'],
            description: 'Dołącz do naszego zespołu jako Deweloper Aplikacji Mobilnych! Poszukujemy osoby z doświadczeniem w tworzeniu aplikacji dla systemów iOS i Android.',
            tasks: ['Tworzenie nowoczesnych aplikacji mobilnych', 'Optymalizacja i utrzymanie istniejących rozwiązań', 'Współpraca z zespołem projektowym'],
            required: ['Doświadczenie w tworzeniu aplikacji mobilnych w React Native, Swift lub Kotlin', 'Znajomość architektury aplikacji mobilnych', 'Umiejętność rozwiązywania problemów'],
            optional: ['Znajomość frameworka Flutter', 'Doświadczenie w pracy z Xamarin', 'Znajomość usług Firebase'],
            benefits: ['Konkurencyjne wynagrodzenie', 'Praca w zespole eksperckim', 'Możliwość udziału w różnorodnych projektach'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Praktyczne zadanie programistyczne', 'Rozmowa z zespołem projektowym'],
            company: '61f8dce5e7a83129bcdb3f1b'
        },
        {
            title: 'DevOps Engineer',
            mode: 'Zdalnie',
            location: 'Gdynia',
            level: 'Senior',
            expiresAt: new Date('2024-04-20'),
            contractType: 'B2B',
            salary: 18000,
            requiredTechnologies: ['Docker', 'Kubernetes', 'Jenkins', 'AWS'],
            optionalTechnologies: ['Terraform', 'Ansible', 'Prometheus'],
            description: 'Dołącz do naszego zespołu jako DevOps Engineer! Poszukujemy doświadczonego specjalisty ds. infrastruktury i automatyzacji procesów.',
            tasks: ['Konfiguracja i utrzymanie systemów DevOps', 'Implementacja rozwiązań do automatyzacji procesów wdrożeniowych', 'Optymalizacja środowiska deweloperskiego'],
            required: ['Doświadczenie w pracy jako DevOps Engineer', 'Znajomość narzędzi do konteneryzacji (Docker, Kubernetes)', 'Umiejętność pracy w chmurze AWS'],
            optional: ['Znajomość narzędzi do infrastruktury jak Terraform i Ansible', 'Doświadczenie w monitorowaniu aplikacji (Prometheus)', 'Certyfikaty z dziedziny DevOps'],
            benefits: ['Konkurencyjne wynagrodzenie', 'Elastyczne godziny pracy', 'Prywatna opieka zdrowotna'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Test praktyczny', 'Rozmowa z zespołem'],
            company: '61f8dce5e7a83129bcdb3f1b'
        },
        {
            title: 'Cybersecurity Specialist',
            mode: 'Stacjonarnie',
            location: 'Łódź',
            level: 'Mid',
            expiresAt: new Date('2024-04-25'),
            contractType: 'Umowa o Pracę',
            salary: 9500,
            requiredTechnologies: ['Firewall', 'Intrusion Detection Systems', 'VPN', 'SIEM Solutions'],
            optionalTechnologies: ['Ethical Hacking', 'Incident Response', 'Cryptography'],
            description: 'Poszukujemy Specjalisty ds. Cyberbezpieczeństwa do pracy w naszym zespole. Oferujemy stabilne zatrudnienie i rozwój zawodowy.',
            tasks: ['Monitoring i analiza zagrożeń', 'Wdrażanie rozwiązań zabezpieczających', 'Przeprowadzanie audytów bezpieczeństwa'],
            required: ['Doświadczenie w obszarze cyberbezpieczeństwa', 'Znajomość narzędzi zabezpieczających (Firewall, IDS, VPN)', 'Umiejętność reagowania na incydenty'],
            optional: ['Znajomość technik Ethical Hacking', 'Doświadczenie w zarządzaniu incydentami', 'Znajomość kryptografii'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Szkolenia z zakresu bezpieczeństwa', 'Możliwość udziału w projektach z obszaru cybersecurity'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Test praktyczny z zakresu bezpieczeństwa', 'Rozmowa z zespołem'],
            company: '61f8dce5e7a83129bcdb3f1c'
        },
        {
            title: 'Quality Assurance Engineer',
            mode: 'Hybrydowo',
            location: 'Kraków',
            level: 'Mid',
            expiresAt: new Date('2024-05-01'),
            contractType: 'Umowa o Pracę',
            salary: 9000,
            requiredTechnologies: ['Selenium', 'Jira', 'TestRail', 'API Testing'],
            optionalTechnologies: ['Cypress', 'Load Testing', 'Performance Testing'],
            description: 'Dołącz do naszego zespołu jako Inżynier ds. Zapewnienia Jakości! Poszukujemy osoby doświadczonej w testowaniu oprogramowania.',
            tasks: ['Tworzenie i wykonywanie testów automatycznych', 'Analiza wymagań funkcjonalnych i niefunkcjonalnych', 'Raportowanie i śledzenie defektów'],
            required: ['Doświadczenie w testowaniu oprogramowania', 'Znajomość narzędzi do automatyzacji testów (Selenium)', 'Umiejętność pracy z systemami do zarządzania testami (Jira, TestRail)'],
            optional: ['Znajomość narzędzi do testowania interfejsów użytkownika (Cypress)', 'Doświadczenie w testowaniu wydajności i obciążeniowym', 'Znajomość technologii związanych z testowaniem API'],
            benefits: ['Stabilne zatrudnienie', 'Możliwość rozwoju zawodowego', 'Przyjazna atmosfera pracy'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Testy praktyczne', 'Rozmowa z zespołem QA'],
            company: '61f8dce5e7a83129bcdb3f1c'
        },
        {
            title: 'UX/UI Designer',
            mode: 'Stacjonarnie',
            location: 'Warszawa',
            level: 'Mid',
            expiresAt: new Date('2024-05-05'),
            contractType: 'Umowa o Pracę',
            salary: 10000,
            requiredTechnologies: ['Figma', 'Adobe XD', 'Sketch'],
            optionalTechnologies: ['InVision', 'Zeplin'],
            description: 'Poszukujemy Designera UX/UI do współpracy przy projektach związanych z projektowaniem interfejsów użytkownika. Oferujemy ciekawą pracę i rozwój w kreatywnym środowisku.',
            tasks: ['Projektowanie interfejsów użytkownika', 'Przeprowadzanie badań użytkowników', 'Tworzenie prototypów i wireframe\'ów'],
            required: ['Doświadczenie w projektowaniu interfejsów UX/UI', 'Znajomość narzędzi do projektowania (Figma, Adobe XD, Sketch)', 'Umiejętność przeprowadzania badań użytkowników'],
            optional: ['Znajomość narzędzi do tworzenia prototypów (InVision, Zeplin)', 'Doświadczenie w tworzeniu animacji interfejsów', 'Zdolności do pracy zespołowej'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Elastyczne godziny pracy', 'Projekty dla klientów z różnych branż'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza portfolio', 'Zadanie projektowe'],
            company: '61f8dce5e7a83129bcdb3f1c'
        },
        {
            title: 'Java Developer',
            mode: 'Zdalnie',
            location: 'Wrocław',
            level: 'Mid',
            expiresAt: new Date('2024-05-10'),
            contractType: 'B2B',
            salary: 12000,
            requiredTechnologies: ['Java', 'Spring Boot', 'Hibernate', 'REST API'],
            optionalTechnologies: ['Microservices', 'Kafka', 'Docker'],
            description: 'Dołącz do zespołu jako Java Developer! Oferujemy interesujące projekty z zakresu aplikacji webowych i mobilnych. Poszukujemy osoby z doświadczeniem w programowaniu w języku Java.',
            tasks: ['Tworzenie i utrzymanie aplikacji w języku Java', 'Implementacja nowych funkcjonalności', 'Optymalizacja kodu i dbałość o wysoką jakość'],
            required: ['Doświadczenie w programowaniu w języku Java', 'Znajomość frameworka Spring Boot', 'Umiejętność pracy z bazą danych przy użyciu Hibernate'],
            optional: ['Doświadczenie w tworzeniu architektury mikroserwisów', 'Znajomość technologii Kafka do przetwarzania strumieni danych', 'Umiejętność pracy z kontenerami Docker'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Możliwość rozwoju zawodowego', 'Praca w zespole ekspertów'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Test praktyczny z programowania Java', 'Rozmowa z liderem projektu'],
            company: '61f8dce5e7a83129bcdb3f1c'
        },
        {
            title: 'Software Engineer',
            mode: 'Stacjonarnie',
            location: 'Gdańsk',
            level: 'Mid',
            expiresAt: new Date('2024-04-20'),
            contractType: 'B2B',
            salary: 12000,
            requiredTechnologies: ['Java', 'Spring Boot', 'Angular', 'MySQL'],
            optionalTechnologies: ['Docker', 'Kubernetes', 'Microservices'],
            description: 'Poszukujemy doświadczonego Software Engineera do pracy nad projektami związanymi z rozwojem oprogramowania.',
            tasks: ['Projektowanie i implementacja nowych funkcji', 'Optymalizacja kodu i wydajności', 'Współpraca z zespołem programistycznym'],
            required: ['Doświadczenie w programowaniu w języku Java', 'Znajomość frameworka Spring Boot', 'Umiejętność pracy w zespole'],
            optional: ['Znajomość kontenerów Docker i Kubernetes', 'Doświadczenie w architekturze mikroserwisów', 'Znajomość frameworka Angular'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Projekty dla klientów z branży IT', 'Praca w nowoczesnym biurze'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Test praktyczny', 'Rozmowa z zespołem'],
            company: '61f8dce5e7a83129bcdb3f1c'
        },
        {
            title: 'Product Manager',
            mode: 'Hybrydowo',
            location: 'Warszawa',
            level: 'Senior',
            expiresAt: new Date('2024-05-01'),
            contractType: 'Umowa o Pracę',
            salary: 18000,
            requiredTechnologies: ['Agile', 'Scrum', 'Jira', 'Product Roadmap'],
            optionalTechnologies: ['Product Backlog Management', 'Market Research'],
            description: 'Dołącz do naszego zespołu jako Product Manager i zarządzaj cyklem życia produktu od koncepcji do wdrożenia.',
            tasks: ['Tworzenie strategii produktowej', 'Zarządzanie backlogiem produktu', 'Współpraca z zespołami developerskimi'],
            required: ['Doświadczenie w zarządzaniu produktami IT', 'Znajomość metodologii Agile i Scrum', 'Umiejętność tworzenia roadmap produktu'],
            optional: ['Znajomość tworzenia User Stories', 'Doświadczenie w zarządzaniu backlogiem produktowym', 'Badania rynkowe i analiza konkurencji'],
            benefits: ['Konkurencyjne wynagrodzenie', 'Elastyczne godziny pracy', 'Możliwość pracy zdalnej'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza przypadku', 'Rozmowa z zespołem zarządzającym'],
            company: '61f8dce5e7a83129bcdb3f1c'
        },
        {
            title: 'DevOps Engineer',
            mode: 'Zdalnie',
            location: 'Kraków',
            level: 'Mid',
            expiresAt: new Date('2024-05-10'),
            contractType: 'B2B',
            salary: 14000,
            requiredTechnologies: ['CI/CD', 'Jenkins', 'Docker', 'Kubernetes'],
            optionalTechnologies: ['Terraform', 'AWS', 'Ansible'],
            description: 'Poszukujemy doświadczonego DevOps Engineera do pracy nad automatyzacją i wdrażaniem rozwiązań w chmurze.',
            tasks: ['Tworzenie i utrzymanie procesów CI/CD', 'Konfiguracja i zarządzanie kontenerami Docker i Kubernetes', 'Automatyzacja infrastruktury'],
            required: ['Doświadczenie w pracy jako DevOps Engineer', 'Znajomość narzędzi CI/CD (Jenkins)', 'Umiejętność pracy z Dockerem i Kubernetes'],
            optional: ['Znajomość Terraforma do automatyzacji', 'Doświadczenie w chmurze AWS', 'Znajomość narzędzi typu Ansible'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca w dynamicznym zespole', 'Możliwość rozwoju zawodowego'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Test praktyczny', 'Rozmowa z zespołem'],
            company: '61f8dce5e7a83129bcdb3f1c'
        },
        {
            title: 'UX/UI Designer',
            mode: 'Stacjonarnie',
            location: 'Poznań',
            level: 'Mid',
            expiresAt: new Date('2024-05-15'),
            contractType: 'Umowa o Pracę',
            salary: 16000,
            requiredTechnologies: ['Adobe XD', 'Figma', 'Sketch', 'User Testing'],
            optionalTechnologies: ['InVision', 'Zeplin', 'Webflow'],
            description: 'Dołącz do naszego zespołu jako UX/UI Designer i uczestnicz w projektowaniu intuicyjnych i estetycznych interfejsów użytkownika.',
            tasks: ['Tworzenie wireframe\'ów i prototypów', 'Współpraca z zespołem developerskim', 'Testowanie użytkownika i analiza feedbacku'],
            required: ['Doświadczenie w projektowaniu interfejsów użytkownika', 'Znajomość narzędzi Adobe XD, Figma, Sketch', 'Umiejętność przeprowadzania testów użytkownika'],
            optional: ['Znajomość narzędzi InVision, Zeplin, Webflow', 'Doświadczenie w projektowaniu responsywnych stron', 'Umiejętność pracy w zespole'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca w inspirującym środowisku', 'Możliwość udziału w konferencjach branżowych'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza portfolio', 'Test projektowy'],
            company: '61f8dce5e7a83129bcdb3f1d'
        },
        {
            title: 'Data Analyst',
            mode: 'Zdalnie',
            location: 'Wrocław',
            level: 'Mid',
            expiresAt: new Date('2024-05-20'),
            contractType: 'B2B',
            salary: 13000,
            requiredTechnologies: ['SQL', 'Python', 'Tableau', 'Data Visualization'],
            optionalTechnologies: ['R', 'Power BI', 'Machine Learning'],
            description: 'Poszukujemy doświadczonego Data Analysta do analizy i interpretacji danych w celu wspierania procesów biznesowych.',
            tasks: ['Przetwarzanie i analiza danych', 'Tworzenie raportów i wizualizacji danych', 'Współpraca z zespołami biznesowymi'],
            required: ['Doświadczenie w analizie danych', 'Znajomość języka SQL i Pythona', 'Umiejętność tworzenia wizualizacji danych'],
            optional: ['Znajomość narzędzi R, Power BI, Machine Learning', 'Doświadczenie w pracy z dużymi zbiorami danych', 'Znajomość narzędzi Big Data'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca zdalna z elastycznym grafikiem', 'Możliwość udziału w szkoleniach'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza przypadku danych', 'Rozmowa z zespołem analitycznym'],
            company: '61f8dce5e7a83129bcdb3f1d'
        },
        {
            title: 'Network Administrator',
            mode: 'Stacjonarnie',
            location: 'Łódź',
            level: 'Mid',
            expiresAt: new Date('2024-05-25'),
            contractType: 'Umowa o Pracę',
            salary: 14000,
            requiredTechnologies: ['Cisco', 'LAN/WAN', 'Firewall', 'Network Security'],
            optionalTechnologies: ['Juniper', 'VoIP', 'Wireless Networking'],
            description: 'Dołącz do naszego zespołu jako Network Administrator i zajmij się utrzymaniem i rozwojem infrastruktury sieciowej firmy.',
            tasks: ['Konfiguracja i utrzymanie sprzętu sieciowego', 'Monitorowanie bezpieczeństwa sieci', 'Wsparcie techniczne dla użytkowników'],
            required: ['Doświadczenie w administracji sieciami komputerowymi', 'Znajomość sprzętu Cisco i technologii LAN/WAN', 'Umiejętność konfiguracji Firewalla'],
            optional: ['Znajomość technologii Juniper, VoIP, Wireless Networking', 'Certyfikaty branżowe w dziedzinie sieci', 'Znajomość zagadnień bezpieczeństwa sieciowego'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Stabilne zatrudnienie w renomowanej firmie', 'Możliwość rozwoju zawodowego'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Test praktyczny z konfiguracji sieci', 'Rozmowa z zespołem IT'],
            company: '61f8dce5e7a83129bcdb3f1d'
        },
        {
            title: 'HR Specialist',
            mode: 'Hybrydowo',
            location: 'Katowice',
            level: 'Mid',
            expiresAt: new Date('2024-05-30'),
            contractType: 'Umowa o Pracę',
            salary: 15000,
            requiredTechnologies: ['HRIS',],
            optionalTechnologies: ['Performance Management', 'HR Analytics'],
            description: 'Poszukujemy doświadczonego HR Specialista do zarządzania procesem rekrutacji i spraw HRowych w firmie.',
            tasks: ['Przeprowadzanie procesów rekrutacyjnych', 'Onboarding nowych pracowników', 'Zarządzanie relacjami z pracownikami'],
            required: ['Doświadczenie w obszarze rekrutacji i HR', 'Umiejętność przeprowadzania wywiadów rekrutacyjnych', 'Znajomość systemów HRIS'],
            optional: ['Znajomość Performance Management, Training and Development', 'Umiejętność przeprowadzania szkoleń', 'Analiza danych HR Analytics'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Elastyczne godziny pracy', 'Praca w dynamicznym środowisku biznesowym'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza przypadku rekrutacyjnego', 'Rozmowa z zespołem HR'],
            company: '61f8dce5e7a83129bcdb3f1d'
        },
        {
            title: 'Frontend Developer',
            mode: 'Zdalnie',
            location: 'Szczecin',
            level: 'Junior',
            expiresAt: new Date('2024-06-05'),
            contractType: 'B2B',
            salary: 10000,
            requiredTechnologies: ['HTML', 'CSS', 'JavaScript', 'React.js'],
            optionalTechnologies: ['Redux', 'TypeScript', 'RWD'],
            description: 'Dołącz do naszego zespołu jako Frontend Developer i bierz udział w tworzeniu nowoczesnych interfejsów webowych.',
            tasks: ['Implementacja interfejsów użytkownika', 'Programowanie w języku JavaScript i React.js', 'Współpraca z zespołem designerskim'],
            required: ['Znajomość HTML, CSS, JavaScript', 'Umiejętność pracy z frameworkiem React.js', 'Zrozumienie zasad Responsive Design'],
            optional: ['Znajomość Redux, TypeScript', 'Doświadczenie w pracy z systemami kontroli wersji', 'Kreatywność i zdolności designerskie'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca zdalna z elastycznym grafikiem', 'Możliwość szkoleń i rozwoju zawodowego'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Test praktyczny z kodowania', 'Rozmowa z zespołem developerskim'],
            company: '61f8dce5e7a83129bcdb3f1d'
        },
        {
            title: 'Marketing Specialist',
            mode: 'Stacjonarnie',
            location: 'Kraków',
            level: 'Mid',
            expiresAt: new Date('2024-06-10'),
            contractType: 'Umowa o Pracę',
            salary: 16000,
            requiredTechnologies: ['Digital Marketing', 'SEO', 'Google Analytics', 'Content Marketing'],
            optionalTechnologies: ['Social Media Marketing', 'Email Marketing', 'SEM'],
            description: 'Poszukujemy doświadczonego Specjalisty ds. Marketingu do planowania i realizacji działań marketingowych.',
            tasks: ['Tworzenie strategii marketingowej', 'Optymalizacja treści pod kątem SEO', 'Analiza danych z Google Analytics'],
            required: ['Doświadczenie w digital marketingu', 'Znajomość SEO, Google Analytics', 'Umiejętność tworzenia strategii content marketingu'],
            optional: ['Znajomość Social Media Marketing, Email Marketing', 'Doświadczenie w kampaniach SEM', 'Kreatywność i innowacyjne podejście'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca w kreatywnym zespole marketingowym', 'Możliwość udziału w szkoleniach branżowych'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza przypadku marketingowego', 'Rozmowa z zespołem marketingowym'],
            company: '61f8dce5e7a83129bcdb3f1d'
        },
        {
            title: 'Mobile App Developer',
            mode: 'Zdalnie',
            location: 'Gdynia',
            level: 'Senior',
            expiresAt: new Date('2024-06-15'),
            contractType: 'B2B',
            salary: 18000,
            requiredTechnologies: ['Swift', 'Kotlin', 'React Native'],
            optionalTechnologies: ['Firebase', 'Realm', 'Flutter'],
            description: 'Dołącz do naszego zespołu jako Mobile App Developer i bierz udział w tworzeniu innowacyjnych aplikacji mobilnych.',
            tasks: ['Programowanie w językach Swift, Kotlin, React Native', 'Projektowanie architektury aplikacji mobilnych', 'Współpraca z zespołem designerskim'],
            required: ['Doświadczenie w programowaniu aplikacji mobilnych', 'Znajomość Swift, Kotlin, React Native', 'Umiejętność projektowania architektury'],
            optional: ['Znajomość Firebase, Realm, Flutter', 'Doświadczenie w pracy z interfejsem API', 'Umiejętność optymalizacji wydajności aplikacji'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca zdalna z elastycznym grafikiem', 'Projekty dla klientów z branży nowoczesnych technologii'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza portfolio projektów mobilnych', 'Test praktyczny kodowania'],
            company: '61f8dce5e7a83129bcdb3f1d'
        },
        {
            title: 'System Administrator',
            mode: 'Stacjonarnie',
            location: 'Warszawa',
            level: 'Senior',
            expiresAt: new Date('2024-07-01'),
            contractType: 'Umowa o Pracę',
            salary: 17000,
            requiredTechnologies: ['Windows Server', 'Active Directory', 'Linux', 'IT Security'],
            optionalTechnologies: ['VMware', 'Powershell'],
            description: 'Dołącz do naszego zespołu jako Administrator Systemów i zajmij się utrzymaniem i zabezpieczaniem infrastruktury IT.',
            tasks: ['Zarządzanie systemami Windows i Linux', 'Implementacja zabezpieczeń IT', 'Wsparcie techniczne dla użytkowników'],
            required: ['Doświadczenie w administracji systemami IT', 'Znajomość Windows Server, Active Directory', 'Umiejętność pracy z systemami Linux'],
            optional: ['Znajomość VMware, Powershell', 'Doświadczenie w administracji siecią', 'Certyfikaty branżowe w dziedzinie IT Security'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Stabilne zatrudnienie w renomowanej firmie', 'Możliwość rozwoju zawodowego'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Test praktyczny z administracji systemami', 'Rozmowa z zespołem IT'],
            company: '61f8dce5e7a83129bcdb3f1d'
        },
        {
            title: 'Graphic Designer',
            mode: 'Zdalnie',
            location: 'Kraków',
            level: 'Mid',
            expiresAt: new Date('2024-07-05'),
            contractType: 'B2B',
            salary: 14000,
            requiredTechnologies: ['Adobe CC', 'Photoshop', 'Illustrator'],
            optionalTechnologies: ['InDesign', 'After Effects', 'UI Design', 'UX Design'],
            description: 'Poszukujemy doświadczonego Grafika, który stworzy kreatywne projekty graficzne dla różnych mediów.',
            tasks: ['Tworzenie projektów graficznych od podstaw', 'Przygotowywanie materiałów reklamowych', 'Współpraca z zespołem marketingowym'],
            required: ['Doświadczenie w projektowaniu graficznym', 'Znajomość narzędzi Adobe Creative Cloud, Photoshop, Illustrator', 'Umiejętność przygotowywania materiałów do druku'],
            optional: ['Znajomość narzędzi InDesign, After Effects', 'Doświadczenie w projektowaniu UI/UX', 'Kreatywność i umiejętność pracy w zespole'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca zdalna z elastycznym grafikiem', 'Projekty dla różnorodnych klientów'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza portfolio projektów graficznych', 'Rozmowa z zespołem projektowym'],
            company: '61f8dce5e7a83129bcdb3f1e'
        },
        {
            title: 'Java Developer',
            mode: 'Stacjonarnie',
            location: 'Poznań',
            level: 'Mid',
            expiresAt: new Date('2024-07-10'),
            contractType: 'Umowa o Pracę',
            salary: 16000,
            requiredTechnologies: ['Java', 'Spring Boot', 'Hibernate', 'REST API'],
            optionalTechnologies: ['Microservices', 'Kafka', 'Angular'],
            description: 'Dołącz do naszego zespołu jako Java Developer i bierz udział w rozwijaniu innowacyjnych projektów.',
            tasks: ['Programowanie w języku Java z wykorzystaniem Spring Boot', 'Implementacja i utrzymanie RESTful API', 'Współpraca z zespołem programistycznym'],
            required: ['Doświadczenie w programowaniu w języku Java', 'Znajomość frameworka Spring Boot', 'Umiejętność pracy z bazami danych SQL'],
            optional: ['Znajomość architektury mikroserwisów, Apache Kafka', 'Doświadczenie w programowaniu front-end (Angular)', 'Zrozumienie zagadnień związanych z bezpieczeństwem API'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Projekty w nowoczesnych technologiach', 'Możliwość rozwoju zawodowego'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Test praktyczny z programowania', 'Rozmowa z zespołem developerskim'],
            company: '61f8dce5e7a83129bcdb3f1e'
        },
        {
            title: 'Content Writer',
            mode: 'Zdalnie',
            location: 'Gdańsk',
            level: 'Junior',
            expiresAt: new Date('2024-07-15'),
            contractType: 'B2B',
            salary: 11000,
            requiredTechnologies: ['SEO', 'Social Media Marketing'],
            optionalTechnologies: ['WordPress', 'Google Analytics', 'Video Scripting'],
            description: 'Poszukujemy kreatywnego Content Writera do tworzenia atrakcyjnych treści online zgodnych z zasadami SEO.',
            tasks: ['Tworzenie unikalnych treści na strony internetowe', 'Prowadzenie bloga i tworzenie wpisów', 'Promocja treści na platformach społecznościowych'],
            required: ['Zdolności redakcyjne i kreatywność', 'Znajomość zasad SEO Copywriting', 'Umiejętność prowadzenia bloga'],
            optional: ['Znajomość systemu WordPress', 'Analiza danych z Google Analytics', 'Tworzenie skryptów wideo'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca zdalna z elastycznym grafikiem', 'Możliwość rozwoju umiejętności pisarskich'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Przykłady dotychczasowych tekstów', 'Test z redakcji treści'],
            company: '61f8dce5e7a83129bcdb3f1e'
        },
        {
            title: 'IT Project Manager',
            mode: 'Stacjonarnie',
            location: 'Wrocław',
            level: 'Senior',
            expiresAt: new Date('2024-07-20'),
            contractType: 'Umowa o Pracę',
            salary: 18000,
            requiredTechnologies: ['Project Management', 'Agile', 'Scrum', 'Risk Management'],
            optionalTechnologies: ['Jira', 'Confluence', 'Stakeholder Communication'],
            description: 'Dołącz do naszego zespołu jako IT Project Manager i zarządzaj projektem od fazy koncepcyjnej do wdrożenia.',
            tasks: ['Zarządzanie cyklem życia projektu', 'Współpraca z zespołem developerskim', 'Komunikacja ze zleceniodawcami'],
            required: ['Doświadczenie w zarządzaniu projektami IT', 'Znajomość metodologii Agile i Scrum', 'Umiejętność zarządzania ryzykiem projektowym'],
            optional: ['Znajomość narzędzi Jira, Confluence', 'Doświadczenie w komunikacji ze zleceniodawcami', 'Certyfikaty w dziedzinie Project Management'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Projekty w nowoczesnych technologiach', 'Możliwość udziału w szkoleniach branżowych'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza przypadku projektowego', 'Rozmowa z zespołem zarządzającym'],
            company: '61f8dce5e7a83129bcdb3f1e'
        },
        {
            title: 'Database Administrator',
            mode: 'Zdalnie',
            location: 'Gdynia',
            level: 'Mid',
            expiresAt: new Date('2024-08-01'),
            contractType: 'B2B',
            salary: 16000,
            requiredTechnologies: ['MySQL', 'Oracle', 'Database Optimization', 'Backup and Recovery'],
            optionalTechnologies: ['MongoDB', 'SQL Server', 'NoSQL Databases'],
            description: 'Poszukujemy doświadczonego Administratora Baz Danych do zarządzania i optymalizacji systemów baz danych.',
            tasks: ['Zarządzanie bazami danych MySQL i Oracle', 'Optymalizacja i monitorowanie wydajności', 'Tworzenie strategii backup i recovery'],
            required: ['Doświadczenie w administracji bazami danych', 'Znajomość MySQL, Oracle', 'Umiejętność optymalizacji baz danych'],
            optional: ['Znajomość MongoDB, SQL Server, NoSQL Databases', 'Doświadczenie w skalowalności baz danych', 'Znajomość narzędzi do backupu i recovery'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca zdalna z elastycznym grafikiem', 'Możliwość udziału w szkoleniach branżowych'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Test praktyczny z administracji bazami danych', 'Rozmowa z zespołem IT'],
            company: '61f8dce5e7a83129bcdb3f1e'
        },
        {
            title: 'Cybersecurity Analyst',
            mode: 'Stacjonarnie',
            location: 'Szczecin',
            level: 'Senior',
            expiresAt: new Date('2024-08-05'),
            contractType: 'Umowa o Pracę',
            salary: 18000,
            requiredTechnologies: ['Cyber Threat Analysis', 'Intrusion Detection', 'Security Information and Event Management (SIEM)', 'Penetration Testing'],
            optionalTechnologies: ['Ethical Hacking', 'Security Certifications (CISSP, CEH)', 'Incident Response'],
            description: 'Dołącz do naszego zespołu jako Cybersecurity Analyst i zajmij się analizą zagrożeń oraz zapewnieniem bezpieczeństwa informatycznego.',
            tasks: ['Analiza zagrożeń cybernetycznych', 'Wdrażanie systemów detekcji intruzów', 'Testy penetracyjne systemów'],
            required: ['Doświadczenie w analizie zagrożeń cybernetycznych', 'Znajomość systemów detekcji intruzów', 'Umiejętność przeprowadzania testów penetracyjnych'],
            optional: ['Znajomość etycznego hakerstwa', 'Posiadanie certyfikatów bezpieczeństwa (CISSP, CEH)', 'Reagowanie na incydenty bezpieczeństwa'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Stabilne zatrudnienie w renomowanej firmie', 'Możliwość udziału w szkoleniach branżowych'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza przypadku z zakresu cyberbezpieczeństwa', 'Rozmowa z zespołem bezpieczeństwa IT'],
            company: '61f8dce5e7a83129bcdb3f1e'
        },
        {
            title: 'UI/UX Researcher',
            mode: 'Zdalnie',
            location: 'Katowice',
            level: 'Mid',
            expiresAt: new Date('2024-08-10'),
            contractType: 'B2B',
            salary: 15000,
            requiredTechnologies: ['User Research', 'Usability Testing', 'Persona Development', 'Information Architecture'],
            optionalTechnologies: ['Heatmaps', 'A/B Testing', 'Wireframing', 'Prototyping'],
            description: 'Poszukujemy doświadczonego Badacza UI/UX, który przeprowadzi badania użytkowników i poprawi doświadczenie użytkownika.',
            tasks: ['Przeprowadzanie badań nad użytkownikami', 'Testy użyteczności interfejsów', 'Tworzenie personas i architektury informacji'],
            required: ['Doświadczenie w badaniach nad użytkownikami', 'Umiejętność przeprowadzania testów użyteczności', 'Tworzenie personas i architektury informacji'],
            optional: ['Znajomość narzędzi takich jak Heatmaps, A/B Testing', 'Doświadczenie w tworzeniu wireframów i prototypów', 'Kreatywność i umiejętność pracy w zespole'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca zdalna z elastycznym grafikiem', 'Możliwość udziału w konferencjach branżowych'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza portfolio projektów badawczych', 'Test badawczy'],
            company: '61f8dce5e7a83129bcdb3f1e'
        },
        {
            title: 'Business Intelligence Analyst',
            mode: 'Stacjonarnie',
            location: 'Wrocław',
            level: 'Mid',
            expiresAt: new Date('2024-08-15'),
            contractType: 'Umowa o Pracę',
            salary: 16000,
            requiredTechnologies: ['Data Analysis', 'SQL', 'Power BI', 'Data Warehousing'],
            optionalTechnologies: ['Python', 'Machine Learning', 'Dashboard Development'],
            description: 'Dołącz do naszego zespołu jako Analityk Business Intelligence i zajmij się analizą danych w celu wspierania decyzji biznesowych.',
            tasks: ['Analiza danych biznesowych', 'Programowanie w języku SQL', 'Tworzenie raportów i dashboardów w Power BI'],
            required: ['Doświadczenie w analizie danych biznesowych', 'Znajomość języka SQL', 'Umiejętność pracy z narzędziami BI, szczególnie Power BI'],
            optional: ['Znajomość Python, Machine Learning', 'Doświadczenie w projektowaniu dashboardów', 'Znajomość zagadnień związanych z hurtowniami danych'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Stabilne zatrudnienie w renomowanej firmie', 'Możliwość udziału w szkoleniach branżowych'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza przypadku danych biznesowych', 'Rozmowa z zespołem analitycznym'],
            company: '61f8dce5e7a83129bcdb3f1e'
        },
        {
            title: 'Full Stack Developer',
            mode: 'Zdalnie',
            location: 'Kraków',
            level: 'Senior',
            expiresAt: new Date('2024-08-20'),
            contractType: 'B2B',
            salary: 18000,
            requiredTechnologies: ['JavaScript', 'Node.js', 'React.js', 'MongoDB'],
            optionalTechnologies: ['GraphQL', 'Docker', 'Express.js'],
            description: 'Poszukujemy doświadczonego Full Stack Developera do tworzenia nowoczesnych aplikacji webowych.',
            tasks: ['Programowanie w języku JavaScript i Node.js', 'Tworzenie interfejsów użytkownika w React.js', 'Implementacja baz danych MongoDB'],
            required: ['Doświadczenie w programowaniu w języku JavaScript', 'Znajomość Node.js, React.js', 'Umiejętność pracy z bazami danych NoSQL'],
            optional: ['Znajomość GraphQL, Docker, Express.js', 'Doświadczenie w pracy z chmurą (AWS, Azure)', 'Zrozumienie zasad projektowania architektury aplikacji'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca zdalna z elastycznym grafikiem', 'Projekty dla klientów z różnych branż'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Test praktyczny z programowania', 'Rozmowa z zespołem developerskim'],
            company: '61f8dce5e7a83129bcdb3f1f'
        },
        {
            title: 'DevOps Engineer',
            mode: 'Stacjonarnie',
            location: 'Poznań',
            level: 'Mid',
            expiresAt: new Date('2024-08-25'),
            contractType: 'Umowa o Pracę',
            salary: 15000,
            requiredTechnologies: ['Docker', 'Kubernetes', 'CI/CD', 'Infrastructure as Code (IaC)'],
            optionalTechnologies: ['Jenkins', 'Terraform', 'AWS', 'Azure', 'Google Cloud'],
            description: 'Dołącz do naszego zespołu jako Inżynier DevOps i bierz udział w projektowaniu i utrzymaniu infrastruktury oraz procesów CI/CD.',
            tasks: ['Konfiguracja i utrzymanie środowisk w kontenerach Docker i Kubernetes', 'Implementacja procesów CI/CD', 'Pisanie skryptów do automatyzacji'],
            required: ['Doświadczenie w pracy jako Inżynier DevOps', 'Znajomość Docker, Kubernetes', 'Umiejętność implementacji procesów CI/CD'],
            optional: ['Znajomość narzędzi takich jak Jenkins, Terraform', 'Doświadczenie w chmurze (AWS, Azure, GCP)', 'Zrozumienie zasad IaC'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Stabilne zatrudnienie w renomowanej firmie', 'Możliwość rozwoju zawodowego'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Test praktyczny z konfiguracji infrastruktury', 'Rozmowa z zespołem DevOps'],
            company: '61f8dce5e7a83129bcdb3f1f'
        },
        {
            title: 'Product Manager',
            mode: 'Hybrydowo',
            location: 'Warszawa',
            level: 'Senior',
            expiresAt: new Date('2024-08-30'),
            contractType: 'Umowa o Pracę',
            salary: 19000,
            requiredTechnologies: ['Product Lifecycle Management', 'Market Analysis', 'User Feedback Analysis', 'Agile'],
            optionalTechnologies: ['Scrum', 'Roadmapping', 'Competitor Analysis'],
            description: 'Poszukujemy doświadczonego Product Managera do zarządzania cyklem życia produktu i analizy rynku.',
            tasks: ['Zarządzanie cyklem życia produktu', 'Analiza rynku i konkurencji', 'Analiza feedbacku od użytkowników'],
            required: ['Doświadczenie w zarządzaniu produktami', 'Znajomość metodologii Agile', 'Umiejętność analizy rynku i feedbacku od użytkowników'],
            optional: ['Znajomość Scrum, Roadmapping', 'Doświadczenie w analizie konkurencji', 'Zrozumienie zasad Product Lifecycle Management'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca w dynamicznym środowisku', 'Możliwość rozwoju zawodowego'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Prezentacja case\'u z zarządzania produktem', 'Rozmowa z zespołem produktowym'],
            company: '61f8dce5e7a83129bcdb3f1f'
        },
        {
            title: 'IT Support Specialist',
            mode: 'Stacjonarnie',
            location: 'Kraków',
            level: 'Junior',
            expiresAt: new Date('2024-09-01'),
            contractType: 'Umowa o Pracę',
            salary: 12000,
            requiredTechnologies: ['IT Troubleshooting', 'Help Desk Support', 'Windows OS', 'Hardware Maintenance'],
            optionalTechnologies: ['Linux Basics', 'Active Directory', 'Remote Desktop Tools'],
            description: 'Poszukujemy Specjalisty ds. Wsparcia IT do udzielania pomocy technicznej i rozwiązywania problemów użytkowników.',
            tasks: ['Rozwiązywanie problemów związanych z IT', 'Obsługa zgłoszeń użytkowników', 'Konserwacja sprzętu komputerowego'],
            required: ['Umiejętność diagnozowania i rozwiązywania problemów IT', 'Doświadczenie w obszarze pomocy technicznej', 'Znajomość systemu Windows'],
            optional: ['Podstawowa znajomość systemu Linux', 'Znajomość Active Directory', 'Doświadczenie w obszarze narzędzi do zdalnego pulpitu'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Stabilne zatrudnienie w renomowanej firmie', 'Możliwość udziału w szkoleniach branżowych'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Test praktyczny z obsługi zgłoszeń', 'Rozmowa z zespołem IT'],
            company: '61f8dce5e7a83129bcdb3f1f'
        },
        {
            title: 'Quality Assurance Engineer',
            mode: 'Zdalnie',
            location: 'Gdańsk',
            level: 'Mid',
            expiresAt: new Date('2024-09-05'),
            contractType: 'B2B',
            salary: 16000,
            requiredTechnologies: ['Test Automation', 'Selenium', 'API Testing', 'Performance Testing'],
            optionalTechnologies: ['Jira', 'TestRail', 'Load Testing Tools'],
            description: 'Dołącz do naszego zespołu jako Inżynier Zapewnienia Jakości i zajmij się testowaniem oprogramowania w celu zapewnienia jego wysokiej jakości.',
            tasks: ['Automatyzacja testów', 'Testowanie interfejsów API', 'Testy wydajnościowe aplikacji', 'Współpraca z zespołem developerskim'],
            required: ['Doświadczenie w automatyzacji testów', 'Znajomość narzędzi takich jak Selenium', 'Testowanie interfejsów API', 'Testy wydajnościowe'],
            optional: ['Znajomość narzędzi takich jak Jira, TestRail', 'Doświadczenie w narzędziach do testów obciążeniowych', 'Zrozumienie zasad Agile w kontekście QA'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca zdalna z elastycznym grafikiem', 'Możliwość rozwoju umiejętności testowania'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Praktyczny test z automatyzacji', 'Rozmowa z zespołem QA i developerskim'],
            company: '61f8dce5e7a83129bcdb3f1f'
        },
        {
            title: 'Network Engineer',
            mode: 'Stacjonarnie',
            location: 'Warszawa',
            level: 'Senior',
            expiresAt: new Date('2024-09-10'),
            contractType: 'Umowa o Pracę',
            salary: 18000,
            requiredTechnologies: ['Cisco Networking', 'Firewall Configuration', 'Routing and Switching', 'VPN Technologies'],
            optionalTechnologies: ['SD-WAN', 'Network Security', 'Network Monitoring Tools'],
            description: 'Poszukujemy doświadczonego Inżyniera Sieciowego do projektowania, konfiguracji i utrzymania infrastruktury sieciowej.',
            tasks: ['Projektowanie i konfiguracja sieci Cisco', 'Konfiguracja zabezpieczeń sieciowych', 'Routowanie i przełączanie', 'Wdrażanie technologii VPN'],
            required: ['Doświadczenie w projektowaniu i konfiguracji sieci Cisco', 'Znajomość konfiguracji firewalli', 'Umiejętność routowania i przełączania'],
            optional: ['Znajomość technologii SD-WAN', 'Znajomość zagadnień związanych z bezpieczeństwem sieciowym', 'Doświadczenie w korzystaniu z narzędzi monitorowania sieci'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Stabilne zatrudnienie w renomowanej firmie', 'Możliwość udziału w szkoleniach branżowych'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza przypadku projektowego z zakresu sieci', 'Rozmowa z zespołem IT'],
            company: '61f8dce5e7a83129bcdb3f1f'
        },
        {
            title: 'HR Specialist',
            mode: 'Zdalnie',
            location: 'Katowice',
            level: 'Mid',
            expiresAt: new Date('2024-09-15'),
            contractType: 'B2B',
            salary: 15000,
            requiredTechnologies: ['Recruitment', 'Employee Relations', 'HRIS', 'Employment Law'],
            optionalTechnologies: ['Performance Management', 'Training and Development', 'HR Analytics'],
            description: 'Dołącz do naszego zespołu jako Specjalista ds. HR i zajmij się rekrutacją, zarządzaniem relacjami z pracownikami i analizą danych HR.',
            tasks: ['Proces rekrutacyjny', 'Zarządzanie relacjami z pracownikami', 'Utrzymywanie i analiza danych w systemie HRIS'],
            required: ['Doświadczenie w prowadzeniu procesów rekrutacyjnych', 'Znajomość prawa pracy', 'Umiejętność zarządzania relacjami z pracownikami'],
            optional: ['Znajomość zagadnień związanych z zarządzaniem wydajnością', 'Doświadczenie w szkoleniach i rozwoju pracowników', 'Umiejętność analizy danych HR'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca zdalna z elastycznym grafikiem', 'Możliwość udziału w szkoleniach branżowych'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza przypadku rekrutacyjnego', 'Rozmowa z zespołem HR'],
            company: '61f8dce5e7a83129bcdb3f1f'
        },
        {
            title: 'Business Analyst',
            mode: 'Hybrydowo',
            location: 'Gdynia',
            level: 'Mid',
            expiresAt: new Date('2024-09-25'),
            contractType: 'Umowa o Pracę',
            salary: 16000,
            requiredTechnologies: ['Business Requirements Gathering', 'Data Analysis', 'Process Mapping', 'Stakeholder Management'],
            optionalTechnologies: ['UML', 'CRM Systems', 'Agile Methodology'],
            description: 'Poszukujemy doświadczonego Analityka Biznesowego do zbierania wymagań biznesowych, analizy danych i mapowania procesów.',
            tasks: ['Gromadzenie wymagań biznesowych', 'Analiza danych biznesowych', 'Tworzenie map procesów', 'Zarządzanie interesariuszami'],
            required: ['Doświadczenie w zbieraniu wymagań biznesowych', 'Znajomość analizy danych biznesowych', 'Tworzenie map procesów biznesowych', 'Zarządzanie interesariuszami'],
            optional: ['Znajomość języka UML', 'Doświadczenie w systemach CRM', 'Znajomość zasad Agile'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca w trybie hybrydowym', 'Możliwość udziału w szkoleniach branżowych'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza przypadku biznesowego', 'Rozmowa z zespołem biznesowym'],
            company: '61f8dce5e7a83129bcdb3f1f'
        },
        {
            title: 'UX/UI Designer',
            mode: 'Zdalnie',
            location: 'Szczecin',
            level: 'Senior',
            expiresAt: new Date('2024-09-30'),
            contractType: 'B2B',
            salary: 18000,
            requiredTechnologies: ['User-Centered Design', 'Wireframing', 'Prototyping', 'Adobe Creative Suite'],
            optionalTechnologies: ['Figma', 'Sketch', 'Interaction Design', 'Responsive Web Design'],
            description: 'Dołącz do naszego zespołu jako Projektant UX/UI i zajmij się tworzeniem intuicyjnych i atrakcyjnych interfejsów użytkownika.',
            tasks: ['Projektowanie zorientowane na użytkownika', 'Tworzenie wireframów i prototypów', 'Praca z narzędziami Adobe Creative Suite'],
            required: ['Doświadczenie w projektowaniu zorientowanym na użytkownika', 'Umiejętność tworzenia wireframów i prototypów', 'Znajomość narzędzi Adobe Creative Suite'],
            optional: ['Znajomość narzędzi takich jak Figma, Sketch', 'Doświadczenie w projektowaniu interakcji', 'Zrozumienie zasad Responsive Web Design'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca zdalna z elastycznym grafikiem', 'Możliwość udziału w konferencjach branżowych'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza portfolio projektów UX/UI', 'Test projektowy'],
            company: '61f8dce5e7a83129bcdb3f20'
        },
        {
            title: 'Data Scientist',
            mode: 'Stacjonarnie',
            location: 'Kraków',
            level: 'Senior',
            expiresAt: new Date('2024-10-05'),
            contractType: 'Umowa o Pracę',
            salary: 19000,
            requiredTechnologies: ['Machine Learning', 'Python', 'Data Analysis', 'Statistical Modeling'],
            optionalTechnologies: ['TensorFlow', 'PyTorch', 'Big Data Technologies'],
            description: 'Poszukujemy doświadczonego Data Scientist do analizy danych, modelowania statystycznego i implementacji rozwiązań opartych na uczeniu maszynowym.',
            tasks: ['Analiza danych', 'Modelowanie statystyczne', 'Programowanie w języku Python', 'Implementacja rozwiązań opartych na uczeniu maszynowym'],
            required: ['Doświadczenie w analizie danych', 'Umiejętność modelowania statystycznego', 'Znajomość języka Python', 'Implementacja rozwiązań opartych na uczeniu maszynowym'],
            optional: ['Znajomość frameworków takich jak TensorFlow, PyTorch', 'Doświadczenie w technologiach Big Data', 'Umiejętność pracy z dużymi zbiorami danych'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Stabilne zatrudnienie w renomowanej firmie', 'Możliwość udziału w szkoleniach branżowych'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza przypadku danych', 'Rozmowa z zespołem analitycznym'],
            company: '61f8dce5e7a83129bcdb3f20'
        },
        {
            title: 'Content Marketing Specialist',
            mode: 'Zdalnie',
            location: 'Wrocław',
            level: 'Mid',
            expiresAt: new Date('2024-10-10'),
            contractType: 'B2B',
            salary: 15000,
            requiredTechnologies: ['Content Strategy', 'SEO', 'Social Media Marketing', 'Copywriting'],
            optionalTechnologies: ['Google Analytics', 'Email Marketing', 'Graphic Design Tools'],
            description: 'Dołącz do naszego zespołu jako Specjalista ds. Content Marketingu i zajmij się tworzeniem strategii treści, pozycjonowaniem SEO i marketingiem społecznościowym.',
            tasks: ['Tworzenie strategii treści', 'Pozycjonowanie treści pod kątem SEO', 'Marketing społecznościowy', 'Tworzenie treści copywritingowej'],
            required: ['Doświadczenie w tworzeniu strategii treści', 'Znajomość SEO', 'Umiejętność marketingu społecznościowego', 'Umiejętność tworzenia treści copywritingowej'],
            optional: ['Znajomość narzędzi takich jak Google Analytics', 'Doświadczenie w email marketingu', 'Umiejętność obsługi narzędzi do projektowania grafiki'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca zdalna z elastycznym grafikiem', 'Możliwość udziału w konferencjach branżowych'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza przypadku content marketingowego', 'Rozmowa z zespołem marketingowym'],
            company: '61f8dce5e7a83129bcdb3f20'
        },
        {
            title: 'Java Software Engineer',
            mode: 'Stacjonarnie',
            location: 'Poznań',
            level: 'Mid',
            expiresAt: new Date('2024-10-15'),
            contractType: 'Umowa o Pracę',
            salary: 16000,
            requiredTechnologies: ['Java', 'Spring Framework', 'RESTful API', 'Database Design'],
            optionalTechnologies: ['Microservices Architecture', 'Hibernate', 'Git'],
            description: 'Poszukujemy doświadczonego Inżyniera Oprogramowania Java do tworzenia nowoczesnych rozwiązań opartych na języku Java i frameworku Spring.',
            tasks: ['Programowanie w języku Java', 'Tworzenie aplikacji przy użyciu Spring Framework', 'Projektowanie baz danych', 'Współpraca z zespołem developerskim'],
            required: ['Doświadczenie w programowaniu w języku Java', 'Znajomość frameworku Spring', 'Tworzenie RESTful API', 'Projektowanie baz danych'],
            optional: ['Znajomość architektury mikroserwisów', 'Znajomość Hibernate', 'Znajomość systemu kontroli wersji Git'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Stabilne zatrudnienie w renomowanej firmie', 'Możliwość rozwoju zawodowego'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Test praktyczny z programowania Java', 'Rozmowa z zespołem developerskim'],
            company: '61f8dce5e7a83129bcdb3f20'
        },
        {
            title: 'Technical Writer',
            mode: 'Zdalnie',
            location: 'Warszawa',
            level: 'Junior',
            expiresAt: new Date('2024-10-20'),
            contractType: 'B2B',
            salary: 12000,
            requiredTechnologies: ['Documentation', 'Content Creation', 'Version Control', 'Technical Research'],
            optionalTechnologies: ['Markdown', 'API Documentation', 'Graphic Design Tools'],
            description: 'Dołącz do naszego zespołu jako Techniczny Redaktor i zajmij się tworzeniem dokumentacji technicznej, treści oraz badań technicznych.',
            tasks: ['Tworzenie dokumentacji technicznej', 'Tworzenie treści technicznych', 'Kontrola wersji dokumentacji', 'Badania techniczne'],
            required: ['Doświadczenie w tworzeniu dokumentacji technicznej', 'Umiejętność tworzenia treści technicznych', 'Kontrola wersji dokumentacji', 'Badania techniczne'],
            optional: ['Znajomość formatu Markdown', 'Tworzenie dokumentacji interfejsów API', 'Umiejętność obsługi narzędzi do projektowania grafiki'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca zdalna z elastycznym grafikiem', 'Możliwość udziału w konferencjach branżowych'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza przykładowej dokumentacji technicznej', 'Rozmowa z zespołem technicznym'],
            company: '61f8dce5e7a83129bcdb3f20'
        },
        {
            title: 'Cybersecurity Analyst',
            mode: 'Hybrydowo',
            location: 'Warszawa',
            level: 'Senior',
            expiresAt: new Date('2024-10-30'),
            contractType: 'Umowa o Pracę',
            salary: 19000,
            requiredTechnologies: ['Incident Response', 'Security Information and Event Management (SIEM)', 'Vulnerability Assessment', 'Network Security'],
            optionalTechnologies: ['Penetration Testing', 'Security Certifications (CISSP, CISM)', 'Threat Intelligence'],
            description: 'Poszukujemy doświadczonego Analityka Cyberbezpieczeństwa do zarządzania inscydentami, monitorowania zagrożeń oraz przeprowadzania ocen podatności.',
            tasks: ['Reakcja na incydenty', 'Monitorowanie systemów SIEM', 'Ocena podatności', 'Zarządzanie bezpieczeństwem sieci'],
            required: ['Doświadczenie w reakcji na incydenty', 'Znajomość systemów SIEM', 'Ocena podatności', 'Zarządzanie bezpieczeństwem sieci'],
            optional: ['Doświadczenie w testach penetracyjnych', 'Certyfikacje z zakresu bezpieczeństwa (CISSP, CISM)', 'Zrozumienie zagadnień Threat Intelligence'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca w trybie hybrydowym', 'Możliwość udziału w szkoleniach branżowych'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza przypadku z obszaru cyberbezpieczeństwa', 'Rozmowa z zespołem IT Security'],
            company: '61f8dce5e7a83129bcdb3f20'
        },
        {
            title: 'Mobile App Developer',
            mode: 'Zdalnie',
            location: 'Kraków',
            level: 'Mid',
            expiresAt: new Date('2024-11-01'),
            contractType: 'B2B',
            salary: 16000,
            requiredTechnologies: ['Swift', 'Kotlin', 'React Native', 'Mobile App Architecture'],
            optionalTechnologies: ['Flutter', 'Xamarin', 'Push Notifications', 'Continuous Integration'],
            description: 'Dołącz do naszego zespołu jako Programista Aplikacji Mobilnych i zajmij się tworzeniem innowacyjnych aplikacji na platformy iOS i Android.',
            tasks: ['Programowanie w języku Swift i Kotlin', 'Tworzenie aplikacji przy użyciu React Native', 'Architektura aplikacji mobilnych', 'Integracja z usługami zewnętrznymi'],
            required: ['Doświadczenie w programowaniu na platformy iOS i Android', 'Znajomość języków Swift i Kotlin', 'Tworzenie aplikacji w React Native', 'Zrozumienie architektury aplikacji mobilnych'],
            optional: ['Znajomość frameworka Flutter', 'Doświadczenie w programowaniu w Xamarin', 'Implementacja powiadomień push', 'Zrozumienie zasad Continuous Integration'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca zdalna z elastycznym grafikiem', 'Możliwość rozwoju w obszarze aplikacji mobilnych'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Praktyczny test programistyczny', 'Rozmowa z zespołem developerskim'],
            company: '61f8dce5e7a83129bcdb3f20'
        },
        {
            title: 'System Administrator',
            mode: 'Stacjonarnie',
            location: 'Poznań',
            level: 'Mid',
            expiresAt: new Date('2024-11-05'),
            contractType: 'Umowa o Pracę',
            salary: 15000,
            requiredTechnologies: ['Linux Administration', 'Windows Server', 'Active Directory', 'Network Configuration'],
            optionalTechnologies: ['VMware', 'Scripting (Bash, PowerShell)', 'Cloud Services (AWS, Azure)', 'ITIL'],
            description: 'Poszukujemy średniozaawansowanego Administratora Systemów do zarządzania środowiskiem IT, konfiguracji sieci i utrzymania serwerów.',
            tasks: ['Administracja systemem Linux', 'Zarządzanie serwerami Windows', 'Konfiguracja Active Directory', 'Konfiguracja sieci'],
            required: ['Doświadczenie w administracji systemem Linux', 'Znajomość serwerów Windows', 'Konfiguracja Active Directory', 'Konfiguracja sieci'],
            optional: ['Znajomość platformy VMware', 'Umiejętność skryptowania (Bash, PowerShell)', 'Doświadczenie w chmurze (AWS, Azure)', 'Zrozumienie ITIL'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Stabilne zatrudnienie w renomowanej firmie', 'Możliwość rozwoju zawodowego'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Test praktyczny z administracji systemem', 'Rozmowa z zespołem IT'],
            company: '61f8dce5e7a83129bcdb3f20'
        },
        {
            title: 'Sales Manager',
            mode: 'Hybrydowo',
            location: 'Wrocław',
            level: 'Senior',
            expiresAt: new Date('2024-11-10'),
            contractType: 'Umowa o Pracę',
            salary: 19000,
            requiredTechnologies: ['Sales Strategy', 'Client Relationship Management', 'Negotiation', 'Sales Analytics'],
            optionalTechnologies: ['Salesforce', 'CRM Systems', 'Business Development', 'E-commerce'],
            description: 'Dołącz do naszego zespołu jako Kierownik Sprzedaży i zajmij się opracowywaniem strategii sprzedażowej, zarządzaniem relacjami z klientami i analizą sprzedaży.',
            tasks: ['Opracowywanie strategii sprzedażowej', 'Zarządzanie relacjami z klientami', 'Negocjacje handlowe', 'Analiza danych sprzedażowych'],
            required: ['Doświadczenie w opracowywaniu strategii sprzedażowej', 'Zarządzanie relacjami z klientami', 'Umiejętność prowadzenia negocjacji handlowych', 'Analiza danych sprzedażowych'],
            optional: ['Znajomość platformy Salesforce', 'Doświadczenie w systemach CRM', 'Rozwój biznesu', 'Zrozumienie rynku e-commerce'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca w trybie hybrydowym', 'Możliwość rozwoju w obszarze zarządzania sprzedażą'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Prezentacja strategii sprzedażowej', 'Rozmowa z zespołem sprzedażowym'],
            company: '6597d2f7a0eeb1a05d7233b0'
        },
        {
            title: 'DevOps Engineer',
            mode: 'Zdalnie',
            location: 'Gdańsk',
            level: 'Mid',
            expiresAt: new Date('2024-11-15'),
            contractType: 'B2B',
            salary: 16000,
            requiredTechnologies: ['Continuous Integration/Continuous Deployment (CI/CD)', 'Container Orchestration (Docker, Kubernetes)', 'Infrastructure as Code (IaC)', 'Automation Scripting'],
            optionalTechnologies: ['Jenkins', 'Ansible', 'Terraform', 'Cloud Services (AWS, Azure)'],
            description: 'Poszukujemy średniozaawansowanego Inżyniera DevOps do wdrażania praktyk CI/CD, zarządzania kontenerami i automatyzacji infrastruktury.',
            tasks: ['Wdrażanie praktyk CI/CD', 'Zarządzanie kontenerami (Docker, Kubernetes)', 'Implementacja Infrastructure as Code', 'Automatyzacja skryptów'],
            required: ['Doświadczenie w wdrażaniu praktyk CI/CD', 'Zarządzanie kontenerami (Docker, Kubernetes)', 'Implementacja Infrastructure as Code', 'Automatyzacja skryptów'],
            optional: ['Doświadczenie w narzędziach takich jak Jenkins, Ansible', 'Znajomość narzędzi do zarządzania infrastrukturą jak Terraform', 'Znajomość chmur (AWS, Azure)'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca zdalna z elastycznym grafikiem', 'Możliwość rozwoju w obszarze DevOps'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Test praktyczny z CI/CD i Infrastructure as Code', 'Rozmowa z zespołem DevOps'],
            company: '6597d2f7a0eeb1a05d7233b0'
        },
        {
            title: 'Financial Analyst',
            mode: 'Stacjonarnie',
            location: 'Katowice',
            level: 'Mid',
            expiresAt: new Date('2024-11-20'),
            contractType: 'Umowa o Pracę',
            salary: 17000,
            requiredTechnologies: ['Financial Modeling', 'Budgeting', 'Data Analysis', 'Microsoft Excel'],
            optionalTechnologies: ['Business Intelligence Tools', 'Financial Reporting', 'ERP Systems'],
            description: 'Poszukujemy średniozaawansowanego Analityka Finansowego do modelowania finansowego, budżetowania i analizy danych finansowych.',
            tasks: ['Modelowanie finansowe', 'Budżetowanie', 'Analiza danych finansowych', 'Praca z arkuszem kalkulacyjnym Microsoft Excel'],
            required: ['Doświadczenie w modelowaniu finansowym', 'Budżetowanie', 'Analiza danych finansowych', 'Znajomość arkusza kalkulacyjnego Microsoft Excel'],
            optional: ['Znajomość narzędzi do Business Intelligence', 'Raportowanie finansowe', 'Doświadczenie w systemach ERP'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Stabilne zatrudnienie w renomowanej firmie', 'Możliwość rozwoju w obszarze finansów'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza przypadku finansowego', 'Rozmowa z zespołem finansowym'],
            company: '6597d2f7a0eeb1a05d7233b0'
        },
        {
            title: 'Product Manager',
            mode: 'Hybrydowo',
            location: 'Warszawa',
            level: 'Senior',
            expiresAt: new Date('2024-11-30'),
            contractType: 'Umowa o Pracę',
            salary: 20000,
            requiredTechnologies: ['Product Lifecycle Management', 'Market Research', 'Product Strategy', 'Agile Methodology'],
            optionalTechnologies: ['Project Management Tools', 'Customer Feedback Analysis', 'UI/UX Understanding'],
            description: 'Poszukujemy doświadczonego Menedżera Produktu do zarządzania cyklem życia produktu, badania rynku, opracowywania strategii produktu i współpracy z zespołem rozwojowym.',
            tasks: ['Zarządzanie cyklem życia produktu', 'Badanie rynku', 'Opracowywanie strategii produktu', 'Współpraca z zespołem rozwojowym'],
            required: ['Doświadczenie w zarządzaniu cyklem życia produktu', 'Badania rynku', 'Opracowywanie strategii produktu', 'Znajomość zasad Agile'],
            optional: ['Znajomość narzędzi do zarządzania projektami', 'Analiza opinii klientów', 'Zrozumienie UI/UX'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca w trybie hybrydowym', 'Możliwość udziału w szkoleniach branżowych'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza przypadku z obszaru zarządzania produktem', 'Rozmowa z zespołem produktowym'],
            company: '6597d2f7a0eeb1a05d7233b0'
        },
        {
            title: 'UI/UX Designer',
            mode: 'Zdalnie',
            location: 'Kraków',
            level: 'Mid',
            expiresAt: new Date('2024-12-01'),
            contractType: 'B2B',
            salary: 17000,
            requiredTechnologies: ['User-Centered Design', 'Wireframing', 'Prototyping', 'Adobe Creative Suite'],
            optionalTechnologies: ['Figma', 'Sketch', 'Interaction Design', 'Responsive Web Design'],
            description: 'Dołącz do naszego zespołu jako Projektant UI/UX i zajmij się tworzeniem intuicyjnych i atrakcyjnych interfejsów użytkownika.',
            tasks: ['Projektowanie zorientowane na użytkownika', 'Tworzenie wireframów i prototypów', 'Praca z narzędziami Adobe Creative Suite'],
            required: ['Doświadczenie w projektowaniu zorientowanym na użytkownika', 'Umiejętność tworzenia wireframów i prototypów', 'Znajomość narzędzi Adobe Creative Suite'],
            optional: ['Znajomość narzędzi takich jak Figma, Sketch', 'Doświadczenie w projektowaniu interakcji', 'Zrozumienie zasad Responsive Web Design'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca zdalna z elastycznym grafikiem', 'Możliwość udziału w konferencjach branżowych'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza portfolio projektów UI/UX', 'Test projektowy'],
            company: '6597d2f7a0eeb1a05d7233b0'
        },
        {
            title: 'Network Engineer',
            mode: 'Stacjonarnie',
            location: 'Poznań',
            level: 'Mid',
            expiresAt: new Date('2024-12-05'),
            contractType: 'Umowa o Pracę',
            salary: 16000,
            requiredTechnologies: ['Routing and Switching', 'Firewall Configuration', 'Network Security', 'Troubleshooting'],
            optionalTechnologies: ['Cisco Technologies', 'Wireless Networking', 'Network Monitoring Tools', 'CCNA/CCNP Certification'],
            description: 'Poszukujemy średniozaawansowanego Inżyniera Sieci do konfiguracji routingu i switchingu, zarządzania bezpieczeństwem sieci oraz rozwiązywania problemów związanych z infrastrukturą sieciową.',
            tasks: ['Konfiguracja routingu i switchingu', 'Konfiguracja firewalli', 'Zarządzanie bezpieczeństwem sieci', 'Rozwiązywanie problemów sieciowych'],
            required: ['Doświadczenie w konfiguracji routingu i switchingu', 'Konfiguracja firewalli', 'Zarządzanie bezpieczeństwem sieci', 'Rozwiązywanie problemów sieciowych'],
            optional: ['Znajomość technologii Cisco', 'Sieci bezprzewodowe', 'Znajomość narzędzi do monitorowania sieci', 'Certyfikacja CCNA/CCNP'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Stabilne zatrudnienie w renomowanej firmie', 'Możliwość rozwoju zawodowego'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Test praktyczny z konfiguracji sieci', 'Rozmowa z zespołem IT'],
            company: '6597d2f7a0eeb1a05d7233b0'
        },
        {
            title: 'Digital Marketing Specialist',
            mode: 'Zdalnie',
            location: 'Wrocław',
            level: 'Mid',
            expiresAt: new Date('2024-12-10'),
            contractType: 'B2B',
            salary: 15000,
            requiredTechnologies: ['SEO', 'SEM', 'Social Media Marketing', 'Content Marketing'],
            optionalTechnologies: ['Google Analytics', 'Email Marketing', 'Conversion Rate Optimization', 'Digital Advertising'],
            description: 'Dołącz do naszego zespołu jako Specjalista ds. Marketingu Cyfrowego i zajmij się optymalizacją treści online, strategią marketingową w mediach społecznościowych i analizą danych marketingowych.',
            tasks: ['Optymalizacja treści online', 'Strategia marketingowa w mediach społecznościowych', 'Analiza danych marketingowych', 'Kampanie reklamowe online'],
            required: ['Doświadczenie w optymalizacji treści online', 'Strategia marketingowa w mediach społecznościowych', 'Znajomość SEO i SEM', 'Marketing treści'],
            optional: ['Znajomość narzędzi takich jak Google Analytics', 'Email Marketing', 'Optymalizacja współczynnika konwersji', 'Reklama cyfrowa'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca zdalna z elastycznym grafikiem', 'Możliwość udziału w konferencjach branżowych'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza przypadku content marketingowego', 'Rozmowa z zespołem marketingowym'],
            company: '6597d2f7a0eeb1a05d7233b0'
        },
        {
            title: 'Java Software Engineer',
            mode: 'Stacjonarnie',
            location: 'Poznań',
            level: 'Mid',
            expiresAt: new Date('2024-12-15'),
            contractType: 'Umowa o Pracę',
            salary: 16000,
            requiredTechnologies: ['Java', 'Spring Framework', 'RESTful API', 'Database Design'],
            optionalTechnologies: ['Microservices Architecture', 'Hibernate', 'Git'],
            description: 'Poszukujemy doświadczonego Inżyniera Oprogramowania Java do tworzenia nowoczesnych rozwiązań opartych na języku Java i frameworku Spring.',
            tasks: ['Programowanie w języku Java', 'Tworzenie aplikacji przy użyciu Spring Framework', 'Projektowanie baz danych', 'Współpraca z zespołem developerskim'],
            required: ['Doświadczenie w programowaniu w języku Java', 'Znajomość frameworku Spring', 'Tworzenie RESTful API', 'Projektowanie baz danych'],
            optional: ['Znajomość architektury mikroserwisów', 'Znajomość Hibernate', 'Znajomość systemu kontroli wersji Git'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Stabilne zatrudnienie w renomowanej firmie', 'Możliwość rozwoju zawodowego'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Test praktyczny z programowania Java', 'Rozmowa z zespołem developerskim'],
            company: '6597d2f7a0eeb1a05d7233b0'
        },
        {
            title: 'Technical Writer',
            mode: 'Zdalnie',
            location: 'Warszawa',
            level: 'Junior',
            expiresAt: new Date('2024-12-20'),
            contractType: 'B2B',
            salary: 12000,
            requiredTechnologies: ['Documentation', 'Content Creation', 'Version Control', 'Technical Research'],
            optionalTechnologies: ['Markdown', 'API Documentation', 'Graphic Design Tools'],
            description: 'Dołącz do naszego zespołu jako Techniczny Redaktor i zajmij się tworzeniem dokumentacji technicznej, treści oraz badań technicznych.',
            tasks: ['Tworzenie dokumentacji technicznej', 'Tworzenie treści technicznych', 'Kontrola wersji dokumentacji', 'Badania techniczne'],
            required: ['Doświadczenie w tworzeniu dokumentacji technicznej', 'Umiejętność tworzenia treści technicznych', 'Kontrola wersji dokumentacji', 'Badania techniczne'],
            optional: ['Znajomość formatu Markdown', 'Tworzenie dokumentacji interfejsów API', 'Umiejętność obsługi narzędzi do projektowania grafiki'],
            benefits: ['Atrakcyjne wynagrodzenie', 'Praca zdalna z elastycznym grafikiem', 'Możliwość udziału w konferencjach branżowych'],
            recruitmentStages: ['Rozmowa rekrutacyjna', 'Analiza przykładowej dokumentacji technicznej', 'Rozmowa z zespołem technicznym'],
            company: '6597d2f7a0eeb1a05d7233b0'
        },
    ]);
}

export default offerSeeder;