export { default as Header } from './header/Header';
export { default as Hero } from './hero/Hero';
export { default as OffersSection } from './offersSection/OffersSection';
export { default as HomeTestimonials } from './homeTestimonials/HomeTestimonials';
export { default as HomeSecurity } from './homeSecurity/HomeSecurity';
export { default as Suppliers } from './suppliers/Suppliers';
export { default as Footer } from './footer/Footer';
export { default as SklepCategories } from './sklepCategories/SklepCategories';
export {default as KontoSettings} from './kontoSettings/KontoSettings';
export {default as KontoMyOrders} from './kontoMyOrders/KontoMyOrders';
export {default as KontoFavorites} from './kontoFavorites/KontoFavorites';