export { default as Header } from './header/Header';
export { default as Hero } from './hero/Hero';
export { default as Discount } from './discount/Discount';
export { default as Services } from './services/Services';
export { default as WhyUs } from './whyUs/WhyUs';
export { default as Testimonials } from './testimonials/Testimonials';
export { default as Footer } from './footer/Footer';
export { default as PostHeader } from './postHeader/PostHeader';
export { default as AdminNav } from './adminNav/AdminNav';
